nome = str(input('digite seu nome completo: ')).strip()
n = nome.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome eh: {}'.format(n[0]))
print('Seu ultimo nome é: {}'.format(n[len(n)-1])) 