n1 = int(input('de qual numero deseja saber a taboada: '))

print('{} x {} = {}'.format(n1, 1, n1*0))
print('{} x {} = {}'.format(n1, 1, n1*1))
print('{} x {} = {}'.format(n1, 1, n1*2))
print('{} x {} = {}'.format(n1, 1, n1*3))
print('{} x {} = {}'.format(n1, 1, n1*4))
print('{} x {} = {}'.format(n1, 1, n1*5))
print('{} x {} = {}'.format(n1, 1, n1*6))
print('{} x {} = {}'.format(n1, 1, n1*7))
print('{} x {} = {}'.format(n1, 1, n1*8))
print('{} x {} = {}'.format(n1, 1, n1*9))
print('{} x {} = {}'.format(n1, 1, n1*10))